server:
  port: 8090

spring:
    datasource:                                           # 数据源的相关配置
      url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      password: 123456
    redis:
      # redis 单机单实例
      database: 1
      host: 192.168.0.36
      port: 6379
      password: imooc

      #redis 哨兵模式
      #database: 1
      #password: imooc
      #sentinel:
        #master: imooc-master
        #nodes: 192.168.0.35:26379,192.168.0.36:26379,192.168.0.37:26379

mybatis:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl